/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controller.Controller;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Conexion;
import modelo.Producte;
import modelo.Stock;

/**
 *
 * @author 9199.joan23
 */
public class VistaProducto extends javax.swing.JInternalFrame {

    Controller producto = new Controller();

    /**
     * Creates new form VistaProducto
     */
    public VistaProducto() {

        initComponents();
        
        this.jTablaProducto.setModel(producto.mostrarProducto());
        producto.Caja(jcCategoriaCaja);
        
        // Cuando inicie  el programa los botones: eliminar, guardar estaran desactivadas
        this.jbEliminar.setEnabled(false);
        this.jbGuardar.setEnabled(false);
        
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtIdPro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtStockActual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtNombrePro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtPrecioPro = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbAñadir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtStockMax = new javax.swing.JTextField();
        jtStockMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcCategoriaCaja = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jtCategoriaId = new javax.swing.JTextField();
        jtStockIdPro = new javax.swing.JTextField();
        jtCategoria = new javax.swing.JTextField();
        jbCambiar = new javax.swing.JButton();
        StokId = new javax.swing.JLabel();
        jtStockId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaProducto = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Producto");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel4.setText("ID");

        jtIdPro.setEditable(false);
        jtIdPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdProActionPerformed(evt);
            }
        });

        jLabel2.setText("Stock");

        jtStockActual.setText(" ");

        jLabel1.setText("Nombre:");

        jtNombrePro.setText(" ");
        jtNombrePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreProActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Elminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbAñadir.setText("Añadir");
        jbAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñadirActionPerformed(evt);
            }
        });

        jLabel5.setText("Stock Max");

        jtStockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtStockMinActionPerformed(evt);
            }
        });

        jLabel6.setText("Stocck Min");

        jcCategoriaCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcCategoriaCaja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcCategoriaCajaItemStateChanged(evt);
            }
        });
        jcCategoriaCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategoriaCajaActionPerformed(evt);
            }
        });

        jLabel7.setText("Categoria");

        jtCategoriaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCategoriaIdActionPerformed(evt);
            }
        });

        jtStockIdPro.setEditable(false);

        jtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCategoriaActionPerformed(evt);
            }
        });

        jbCambiar.setText("Cambiar");

        StokId.setText("Stocck Id");

        jtStockId.setEditable(false);
        jtStockId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtStockIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtPrecioPro)
                            .addComponent(jtIdPro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtStockActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jtNombrePro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtStockIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jtStockMax))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(StokId))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtStockId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jtStockMin))))
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcCategoriaCaja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbAñadir)
                                .addGap(18, 18, 18)
                                .addComponent(jbEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbGuardar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jbCambiar)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtPrecioPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtStockIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtStockMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtStockMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtStockId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StokId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcCategoriaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCambiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAñadir)
                    .addComponent(jbEliminar)
                    .addComponent(jbGuardar))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Producto"));

        jTablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaProducto);

        jLabel8.setText("buscar");

        jbBuscar.setText("buscar");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(152, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(112, 112, 112))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtIdProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdProActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:

        //primero ver de que accion viene si de guardar o demodificar 
        //validar
        if (this.jtNombrePro.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un Nombre para el producto");
            jtNombrePro.requestFocus();
            return;
        }
        if (this.jtStockActual.getText().length() == 0) {

            JOptionPane.showConfirmDialog(rootPane, "Campo obligatorio  para el producto");

            // boolean num=ControllerFactura.isNumeric(this.jtStock.getText());
            jtStockActual.requestFocus();
            return;
        }
        //  ControllerFactura.isNumeric(this.jtStock.getText())
        if (!Controller.isNumeric(this.jtStockActual.getText())) {

            JOptionPane.showConfirmDialog(rootPane, "Debe ser un numero ");

            boolean num=Controller.isNumeric(this.jtStockActual.getText());
            jtStockActual.requestFocus();
            return;
        }

        //
       

       //producte.addProducteStock(p, s);
       
        // Activamos el boton añadir, eliminar
        this.jbAñadir.setEnabled(true);
        this.jbEliminar.setEnabled(false);
        
        if (this.jbGuardar.getText()=="Guardar"){
        String nombre = this.jtNombrePro.getText();
        double precio = Double.parseDouble(this.jtPrecioPro.getText());
        int stock = Integer.parseInt(this.jtStockActual.getText());
        int stockM = Integer.parseInt(this.jtStockMax.getText());
        int stockm = Integer.parseInt(this.jtStockMin.getText());
        int idcategoria = Integer.parseInt(this.jtCategoriaId.getText());

        Stock s = new Stock(stock, stockM, stockm);

        Producte p = new Producte(nombre, precio, idcategoria);
        producto.añadirProductoEstoc(p, s);
        }
        if (this.jbGuardar.getText()=="Modificar"){
            
        String nombre = this.jtNombrePro.getText();
        double precio = Double.parseDouble(this.jtPrecioPro.getText());
        int stock = Integer.parseInt(this.jtStockActual.getText());
        int stockM = Integer.parseInt(this.jtStockMax.getText());
        int stockm = Integer.parseInt(this.jtStockMin.getText());
        int idcategoria = Integer.parseInt(this.jtCategoriaId.getText());

        Stock s = new Stock(stock, stockM, stockm);

        Producte p = new Producte(nombre, precio, idcategoria);
        producto.modifcarProductoEstoc(p, s);
        }
       
        this.jbAñadir.setEnabled(true);
         this.jbEliminar.setEnabled(true);
         this.jbGuardar.setEnabled(false);
     
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtNombreProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreProActionPerformed

    private void jbAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñadirActionPerformed
        // TODO add your handling code here:

        //poner todo en blanco
        this.jtNombrePro.setText("");
        this.jtStockActual.setText("");
        this.jtIdPro.setText("");
        this.jtStockIdPro.setText("");
        this.jtPrecioPro.setText("");
        this.jtCategoriaId.setText("");
        this.jtStockMax.setText("");
        this.jtStockMin.setText("");
        this.jtCategoria.setText("");
        this.jtStockId.setText("");
        
        // indicamos si el boton guardar se llama modificar lo cambiamos a guardar
        
         //Modificamos el boton modificar  para que pase a guardar
         if(jbGuardar.getText()=="Modificar"){
        this.jbGuardar.setText("Guardar");
         }
         
      
         // Desactivamos los botones añadir y eliminar
         this.jbAñadir.setEnabled(false);
         this.jbEliminar.setEnabled(false);
         //Activamos los botones guardar 
         this.jbGuardar.setEnabled(true);
         
        //inciamos la accion guardar que viene del controller
        
        
    }//GEN-LAST:event_jbAñadirActionPerformed

    private void jTablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaProductoMouseClicked
        // TODO add your handling code here:

        //System.out.println("Hola");
        //Modificamos el boton guardar para que pase a modificar
        this.jbGuardar.setText("Modificar");
        //Marcar la fila selecionado al presionar click
        int fila = jTablaProducto.rowAtPoint(evt.getPoint());
        //Pasa el parametro
        jtIdPro.setText(String.valueOf(jTablaProducto.getValueAt(fila, 0)));
        jtStockIdPro.setText(String.valueOf(jTablaProducto.getValueAt(fila, 0)));
        jtNombrePro.setText(String.valueOf(jTablaProducto.getValueAt(fila, 1)));
        jtPrecioPro.setText(String.valueOf(jTablaProducto.getValueAt(fila, 2)));
        jtCategoriaId.setText(String.valueOf(jTablaProducto.getValueAt(fila, 4)));
        jtStockMax.setText(String.valueOf(jTablaProducto.getValueAt(fila, 5)));
        jtStockMin.setText(String.valueOf(jTablaProducto.getValueAt(fila, 6)));
        jtStockActual.setText(String.valueOf(jTablaProducto.getValueAt(fila, 7)));
        jtCategoria.setText(String.valueOf(jTablaProducto.getValueAt(fila, 8)));
        jtStockId.setText(String.valueOf(jTablaProducto.getValueAt(fila, 9)));
        

        //Desahibilitar los botones de añadir y eliminar
        
         this.jbAñadir.setEnabled(true);
         this.jbEliminar.setEnabled(true);
         this.jbGuardar.setEnabled(true);
         
    }//GEN-LAST:event_jTablaProductoMouseClicked

    private void jcCategoriaCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategoriaCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCategoriaCajaActionPerformed

    private void jtCategoriaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCategoriaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCategoriaIdActionPerformed

    private void jcCategoriaCajaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcCategoriaCajaItemStateChanged
        Categoria ca = (Categoria) this.jcCategoriaCaja.getSelectedItem();
        this.jtCategoriaId.setText(String.valueOf(ca.getCategoria_id()));
    }//GEN-LAST:event_jcCategoriaCajaItemStateChanged

    private void jtStockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtStockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtStockMinActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
      
    
        int pro_id  = Integer.parseInt(this.jtIdPro.getText());
        int id_stock = Integer.parseInt(this.jtStockId.getText());


        Stock s = new Stock(id_stock);

        Producte p = new Producte(pro_id);

        
        producto.eliminarProductoEstoc(p,s);
         this.jbEliminar.setEnabled(false);
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCategoriaActionPerformed

    private void jtStockIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtStockIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtStockIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StokId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaProducto;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbAñadir;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCambiar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcCategoriaCaja;
    private javax.swing.JTextField jtCategoria;
    private javax.swing.JTextField jtCategoriaId;
    private javax.swing.JTextField jtIdPro;
    private javax.swing.JTextField jtNombrePro;
    private javax.swing.JTextField jtPrecioPro;
    private javax.swing.JTextField jtStockActual;
    private javax.swing.JTextField jtStockId;
    private javax.swing.JTextField jtStockIdPro;
    private javax.swing.JTextField jtStockMax;
    private javax.swing.JTextField jtStockMin;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
